RELX_REPLACE_OS_VARS ?= true
RTGW_VMARGS_SNAME ?= rtgw
RTGW_VMARGS_COOKIE ?= rtgw
RTGW_VMARGS_LIMIT_ETS ?= 1024
RTGW_VMARGS_LIMIT_PROCESSES ?= 100000
RTGW_VMARGS_LIMIT_PORTS ?= 10000
RTGW_VMARGS_LIMIT_ATOMS ?= 100000
RTGW_VMARGS_ASYNC_THREADS ?= 8
RTGW_VMARGS_KERNEL_POLL ?= true
RTGW_APP_LOGGER_LOG_ROOT ?= $(RTGW_DIR_LOGS)
RTGW_APP_LOGGER_LOG_LEVEL ?= debug

RTGW_APP_GRPC_LISTENER_PORT ?= 8837
RTGW_APP_TUNNEL_LISTENER_PORT ?= 9837
