RELX_REPLACE_OS_VARS ?= true
ECHO_VMARGS_SNAME ?= echo
ECHO_VMARGS_COOKIE ?= echo
ECHO_VMARGS_LIMIT_ETS ?= 1024
ECHO_VMARGS_LIMIT_PROCESSES ?= 100000
ECHO_VMARGS_LIMIT_PORTS ?= 10000
ECHO_VMARGS_LIMIT_ATOMS ?= 100000
ECHO_VMARGS_ASYNC_THREADS ?= 8
ECHO_VMARGS_KERNEL_POLL ?= true
ECHO_APP_LOGGER_LOG_ROOT ?= $(ECHO_DIR_LOGS)
ECHO_APP_LOGGER_LOG_LEVEL ?= debug

ECHO_APP_GRPC_LISTENER_PORT ?= 8237
ECHO_APP_ROOM_LISTENER_PORT ?= 9237
