-define(EXIT_CODE_OK, 0).
-define(EXIT_CODE_UNKNOWN, 1).

-define(EXIT_CODE_NODE_INACCESSIBLE, 128).
-define(EXIT_CODE_BADRPC, 129).

-define(EXIT_CODE_GETOPT_FAILED, 130).
-define(EXIT_CODE_INVALID_ACTION, 131).
-define(EXIT_CODE_MISSING_ARGS, 132).
-define(EXIT_CODE_INVALID_ARGS, 133).

-define(EXIT_CODE_REMOTE_ERROR, 134).