ROUTER_APP_LOGGER_LOG_ROOT = $(TEST_ROOT)/router_logs

ROUTER_APP_HASHRING_BUCKETS_PO2 = 4
ROUTER_APP_HASHRING_NODES_PO2 = 2
ROUTER_APP_GRPC_LISTENER_PORT = 8137
ROUTER_APP_GRPC_SESSION_INACTIVITY_LIMIT_MS = 100
