name: Perform all checks
run-name: Perform all checks (${{ github.ref_name }} / ${{ github.sha }})
on: [push]

permissions:
  contents: read

jobs:

  check:
    strategy:
      matrix:
        version: [25]
    runs-on: ubuntu-latest

    container:
      image: erlang:${{ matrix.version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    ## cached files
    - name: Cache test build
      id: test-build
      uses: actions/cache@v3
      with:
        path: _build/test
        key: ${{ runner.os }}-test-build-${{ hashFiles('rebar.lock') }}
    - name: Cache test tools (lux)
      id: test-tools-lux
      uses: actions/cache@v3
      with:
        path: _tools/lux
        key: ${{ runner.os }}-test-tools-lux-${{ hashFiles('_tools/.lux_version') }}
    - name: Cache test plt
      uses: actions/cache@v3
      id: test-plt
      with:
        path: .plt
        key: ${{ runner.os }}-test-plt-${{ hashFiles('rebar.lock') }}

    ## dialyzer run
    - name: Print ENV
      run: printenv

    ## dialyzer run
    - name: Dialyzer
      run: make dialyze

    ## unit tests
    - name: EUnit
      run: make unit-tests

    ## common tests
    - name: Common Test
      run: make common-tests
    - name: Upload Common Test Artifacts
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: common-tests-artifacts-${{ github.sha }}
        path: test/ct
        retention-days: 3

    ## lux tests
    - name: Install jq
      uses: dcarbone/install-jq-action@v1.0.1
    - name: Lux
      run: make lux-tests
    - name: Upload Lux Artifacts
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: lux-tests-artifacts-${{ github.sha }}
        path: test/lux
        retention-days: 3
